version: '3.3'
services:
  vite:
    build: ./build
    ports:
      - "3000:3000"
    command: yarn serve
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - vite
    command: nginx -g daemon off