version: '3.9'
services:
  my-vite-react-app:
    build: .
    ports:
      - "5147:5147"
    command: yarn dev
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - my-vite-react-app